Repository corda/corda-gradle-plugins, pull requests merged in 2018-11, with the labels that each got.

#122 CORDA-2101: Gradle plugins can now be published to the gradle plugins publishing portal
  api-scanner/build.gradle
  build.gradle
  cordapp/build.gradle
  cordformation/build.gradle
  gradle/wrapper/gradle-wrapper.jar
  jar-filter/build.gradle
  publish-utils/build.gradle
  quasar-utils/build.gradle
Labels: enhancement

#137 Restrict Kotlin API to match the one that Gradle uses.
  build.gradle
Labels: trivial

#138 Fix credentials for publishing to Artifactory.
  build.gradle
Labels: bug

#140 CORDA-2237: Replace shaded kotlin-metadata with kotlinx-metadata-jvm.
  build.gradle
  jar-filter/build.gradle
  jar-filter/kotlin-metadata/build.gradle
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Elements.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/KotlinAwareVisitor.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTransformer.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerVisitor.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/SanitisingTransformer.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/ClassMetadata.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/FileMetadata.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/MetadataTools.kt
  settings.gradle
Labels: bug
