Repository corda/corda-gradle-plugins, pull requests merged in 2019-10, with the labels that each got.

#255 Small tweaks to Cordformation.
  cordformation/src/main/kotlin/net/corda/plugins/Node.kt
  cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
Labels: trivial

#257 Add support for OU when generating nodes directories.
  CONTRIBUTORS.md
  changelog.md
  cordformation/src/main/kotlin/net/corda/plugins/Node.kt
  cordformation/src/test/kotlin/net/corda/plugins/BaseformTest.kt
  cordformation/src/test/kotlin/net/corda/plugins/CordformTest.kt
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle
Labels: enhancement

#258 make 5005 & 7005 port configuare to avoid port confict if running two…
  cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
Labels: enhancement

#261 Maintenance on Gradle files.
  api-scanner/build.gradle
  build.gradle
  cordapp/build.gradle
  cordapp/src/test/kotlin/net/corda/plugins/CordappGradleConfigurationsTest.kt
  cordapp/src/test/kotlin/net/corda/plugins/CordappLibraryGradleConfigurationsTest.kt
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
  jar-filter/build.gradle
  jar-filter/src/test/resources/repositories.gradle
  jar-filter/unwanteds/build.gradle
Labels: trivial

#260 Minor refactor to NodeRunner to prepare for release.
  CONTRIBUTORS.md
  changelog.md
  cordformation/src/noderunner/kotlin/net/corda/plugins/NodeRunner.kt
Labels: bug

#263 CORDA-3377: Add `excludePackages` to the `scanApi` task.
  api-scanner/README.md
  api-scanner/src/main/java/net/corda/plugins/ApiPrintWriter.java
  api-scanner/src/main/java/net/corda/plugins/ApiScanner.java
  api-scanner/src/main/java/net/corda/plugins/ScanApi.java
  api-scanner/src/main/java/net/corda/plugins/ScannerExtension.java
  api-scanner/src/test/java/net/corda/plugins/ClassWithInternalAnnotationTest.java
  api-scanner/src/test/java/net/corda/plugins/ExcludePackageTest.java
  api-scanner/src/test/resources/class-internal-annotation/java/net/corda/example/AnnotatedClass.java
  api-scanner/src/test/resources/class-internal-annotation/java/net/corda/example/InternalClass.java
  api-scanner/src/test/resources/exclude-package/build.gradle
  api-scanner/src/test/resources/exclude-package/java/net/corda/example/unwanted/UnwantedClass.java
  api-scanner/src/test/resources/exclude-package/java/net/corda/example/unwanted/very/VeryUnwantedClass.java
  api-scanner/src/test/resources/exclude-package/java/net/corda/example/wanted/WantedClass.java
  changelog.md
Labels: enhancement
