Repository corda/corda-gradle-plugins, pull requests merged in 2020-02, with the labels that each got.

#280 CORDA-3570: Backport removal of cordapp plugin as a dependency.
  README.md
  changelog.md
  cordapp/build.gradle
  cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
  cordapp/src/main/kotlin/net/corda/plugins/CordappUtils.kt
  cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
  cordapp/src/main/kotlin/net/corda/plugins/Signing.kt
  cordapp/src/main/template/SigningOptions.kt
  cordapp/src/test/kotlin/net/corda/plugins/VersionComparatorTest.kt
  cordformation/build.gradle
  cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
  cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
  cordformation/src/main/kotlin/net/corda/plugins/CordformationUtils.kt
  cordformation/src/main/kotlin/net/corda/plugins/KeyGenAndSigningOptions.kt
  cordformation/src/main/kotlin/net/corda/plugins/Node.kt
  cordformation/src/main/kotlin/net/corda/plugins/utils/Utils.kt
  publish-utils/build.gradle
  publish-utils/src/main/groovy/net/corda/plugins/publish/MavenDependencyExtension.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/MavenMapper.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/ProjectPublishExtension.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/PublishTasks.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/bintray/BintrayConfigExtension.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/bintray/Developer.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/bintray/License.groovy
  quasar-utils/build.gradle
  quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarExtension.groovy
  quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
  quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy
  quasar-utils/src/test/groovy/net/corda/plugins/quasar/Utilities.groovy
Labels: backport, bug

#279 CORDA-3570: Remove runtime dependencies between plugins.
  README.md
  changelog.md
  cordapp/build.gradle
  cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
  cordapp/src/main/kotlin/net/corda/plugins/CordappUtils.kt
  cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
  cordapp/src/main/kotlin/net/corda/plugins/Signing.kt
  cordapp/src/main/template/SigningOptions.kt
  cordapp/src/test/kotlin/net/corda/plugins/VersionComparatorTest.kt
  cordformation/build.gradle
  cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
  cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
  cordformation/src/main/kotlin/net/corda/plugins/CordformationUtils.kt
  cordformation/src/main/kotlin/net/corda/plugins/KeyGenAndSigningOptions.kt
  cordformation/src/main/kotlin/net/corda/plugins/Node.kt
  cordformation/src/main/kotlin/net/corda/plugins/utils/Utils.kt
  publish-utils/build.gradle
  publish-utils/src/main/groovy/net/corda/plugins/publish/MavenDependencyExtension.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/MavenMapper.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/ProjectPublishExtension.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/PublishTasks.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/bintray/BintrayConfigExtension.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/bintray/Developer.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/bintray/License.groovy
  quasar-utils/build.gradle
  quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarExtension.groovy
  quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
  quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy
  quasar-utils/src/test/groovy/net/corda/plugins/quasar/Utilities.groovy
Labels: bug

#282 CORDA-3586: Fix Gradle task validation warnings for cordformation.
  cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
  cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Labels: bug

#283 CORDA-3586: Backport fixes for Gradle cordformation task validation warnings.
  cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
  cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Labels: backport, bug

#284 NOTICK: Tidy up our usage of Gradle API.
  api-scanner/build.gradle
  api-scanner/src/main/java/net/corda/plugins/GenerateApi.java
  api-scanner/src/main/java/net/corda/plugins/ScanApi.java
  build.gradle
  cordapp/build.gradle
  cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
  cordformation/build.gradle
  cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
  jar-filter/build.gradle
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
  jar-filter/unwanteds/build.gradle
  publish-utils/build.gradle
Labels: trivial

#285 BACKPORT: Tidy up usage of Gradle API.
  api-scanner/build.gradle
  api-scanner/src/main/java/net/corda/plugins/GenerateApi.java
  api-scanner/src/main/java/net/corda/plugins/ScanApi.java
  cordapp/build.gradle
  cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
  cordformation/build.gradle
  cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
  jar-filter/build.gradle
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
  jar-filter/unwanteds/build.gradle
  publish-utils/build.gradle
Labels: backport, trivial

#286 NOTICK: Configure properties for Gradle test projects.
  api-scanner/src/test/resources/gradle.properties
  cordapp/src/test/resources/gradle.properties
  cordformation/src/test/resources/gradle.properties
  jar-filter/src/test/resources/gradle.properties
  quasar-utils/src/test/resources/gradle.properties
Labels: trivial

#281 NOTICK: Update the top-level README with a summary of each plugin.
  README.md
Labels: enhancement

#288 Fix data source url override
  CONTRIBUTORS.md
  cordformation/src/main/kotlin/net/corda/plugins/Node.kt
Labels: bug
