Repository corda/corda-gradle-plugins, pull requests merged in 2021-02, with the labels that each got.

#365 CORE-830: Upgrade JarFilter to use ASM 9.0.
  changelog.md
  gradle.properties
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/FilterTransformer.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerVisitor.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetadataTransformer.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/SanitisingTransformer.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/Utils.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteJava15PermittedSubclassTest.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/DeleteJava15SealedClassTest.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/asm/MetadataTools.kt
  jar-filter/src/test/resources/delete-java15-permitted-subclass/build.gradle
  jar-filter/src/test/resources/delete-java15-permitted-subclass/java/net/corda/gradle/UnwantedSubclass.java
  jar-filter/src/test/resources/delete-java15-permitted-subclass/java/net/corda/gradle/WantedSealedClass.java
  jar-filter/src/test/resources/delete-java15-permitted-subclass/java/net/corda/gradle/WantedSubclass.java
  jar-filter/src/test/resources/delete-java15-sealed-class/build.gradle
  jar-filter/src/test/resources/delete-java15-sealed-class/java/net/corda/gradle/DeletableSealedClass.java
  jar-filter/src/test/resources/delete-java15-sealed-class/java/net/corda/gradle/SealedSubclass.java
Labels: technical debt

#366 CORE-853: Do not log passwords when signing CorDapp jars.
  changelog.md
  cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
  cordapp/src/test/kotlin/net/corda/plugins/CordappTest.kt
Labels: bug

#369 NOTICK: Resolve Gradle deprecation warnings in API Scanner.
  api-scanner/src/main/java/net/corda/plugins/apiscanner/GenerateApi.java
  api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java
Labels: technical debt

#371 NOTICK: Resolve Gradle deprecation warnings in API Scanner.
  api-scanner/src/main/java/net/corda/plugins/apiscanner/GenerateApi.java
  api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java
Labels: technical debt

#372 CORE-855: Upgrade to Gradle 6.7.1.
  api-scanner/src/test/resources/kotlin.gradle
  build.gradle
  changelog.md
  cordformation/src/main/kotlin/net/corda/plugins/Baseform.kt
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  jar-filter/build.gradle
  settings.gradle
Labels: enhancement

#373 CORE-855: Disable Gradle's auto-provisioning for JDKs.
  gradle.properties
Labels: trivial

#375 CORE-855: Resolve Gradle deprecation warnings in JarFilter.
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
Labels: technical debt, trivial

#376 CORE-855: Resolve Gradle deprecation warnings in JarFilter. (#375)
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
Labels: backport, technical debt

#374 CORE-855: Update quasar-utils plugin to use OSGi Quasar 0.8.x.
  README.md
  changelog.md
  quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarExtension.groovy
  quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
  quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarPluginTest.groovy
  quasar-utils/src/test/groovy/net/corda/plugins/quasar/QuasarSuspendableTest.groovy
  quasar-utils/src/test/resources/repositories.gradle
Labels: enhancement

#378 CORE-855: Update Cordformation plugin for Gradle 6.7.1.
  cordformation/build.gradle
  cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
  cordformation/src/main/kotlin/net/corda/plugins/CordformationUtils.kt
  cordformation/src/main/kotlin/net/corda/plugins/Dockerform.kt
  cordformation/src/main/kotlin/net/corda/plugins/Node.kt
  cordformation/src/test/resources/net/corda/plugins/DeployDockerImage.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordapp.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappBackwardsCompatibility.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappConfig.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithDocker.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithNetworkConfigWithDocker.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithCordappWithOU.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExternalDBSettingsWithDocker.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithExtraCommandForDbSchema.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithLocallyBuildCordappAndConfig.gradle
  cordformation/src/test/resources/net/corda/plugins/DeploySingleNodeWithNetworkParameterOverrides.gradle
  cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithDocker.gradle
  cordformation/src/test/resources/net/corda/plugins/DeployThreeNodeCordappWithExternalDBSettingsWithNetworkConfigWithDocker.gradle
  cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithDocker.gradle
  cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithExternalService.gradle
  cordformation/src/test/resources/net/corda/plugins/DeployTwoNodeCordappWithExternalServiceNoOption.gradle
Labels: enhancement

#379 CORE-855: Adjust definition of cordaProvided configuration.
  README.md
  cordformation/src/main/kotlin/net/corda/plugins/Cordformation.kt
  cordformation/src/main/kotlin/net/corda/plugins/CordformationUtils.kt
  publish-utils/src/main/groovy/net/corda/plugins/publish/PublishConfigurationProjectListener.groovy
  publish-utils/src/main/groovy/net/corda/plugins/publish/PublishPlugin.groovy
  quasar-utils/src/main/groovy/net/corda/plugins/quasar/QuasarPlugin.groovy
Labels: enhancement

#380 CORE-855: Update legacy cordapp plugin for Gradle 6.7.1.
  README.md
  cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
  cordapp/src/main/kotlin/net/corda/plugins/SignJar.kt
Labels: enhancement

#381 CORE-727 added Flask plugin
  flask/README.md
  flask/build.gradle
  flask/flask-common/build.gradle
  flask/flask-common/src/main/java/net/corda/flask/common/Flask.java
  flask/flask-common/src/main/java/net/corda/flask/common/LockFile.java
  flask/flask-heartbeat-agent/build.gradle
  flask/flask-heartbeat-agent/src/main/java/net/corda/flask/HeartbeatAgent.java
  flask/flask-launcher/build.gradle
  flask/flask-launcher/src/lockFileTest/java/net/corda/flask/launcher/LockFileTestMain.java
  flask/flask-launcher/src/main/java/net/corda/flask/launcher/JarCache.java
  flask/flask-launcher/src/main/java/net/corda/flask/launcher/JavaProcessBuilder.java
  flask/flask-launcher/src/main/java/net/corda/flask/launcher/Launcher.java
  flask/flask-launcher/src/test/java/net/corda/flask/launcher/JavaProcessBuilderTest.java
  flask/flask-launcher/src/test/java/net/corda/flask/launcher/LockFileTest.java
  flask/src/main/groovy/net/corda/gradle/flask/FlaskPlugin.groovy
  flask/src/main/java/net/corda/gradle/flask/FlaskJarTask.java
  flask/src/main/java/net/corda/gradle/flask/HeartbeatAgentResource.java
  flask/src/main/java/net/corda/gradle/flask/JavaAgent.java
  flask/src/main/java/net/corda/gradle/flask/LauncherResource.java
  flask/src/test/groovy/net/corda/gradle/flask/FlaskPluginTest.groovy
  flask/src/test/resources/testProject/build.gradle
  flask/src/test/resources/testProject/settings.gradle
  flask/src/test/resources/testProject/src/flask/java/net/corda/gradle/flask/test/TestLauncher.java
  flask/src/test/resources/testProject/src/main/java/net/corda/gradle/flask/test/AlternativeMain.java
  flask/src/test/resources/testProject/src/main/java/net/corda/gradle/flask/test/Main.java
  flask/src/test/resources/testProject/testAgent/build.gradle
  flask/src/test/resources/testProject/testAgent/src/main/java/net/corda/gradle/flask/test/agent/JavaAgent.java
  gradle.properties
  settings.gradle
Labels: enhancement

#382 NOTICK: Resolve simple warings in flask plugin.
  flask/build.gradle
  flask/flask-common/src/main/java/net/corda/flask/common/Flask.java
  flask/flask-launcher/src/main/java/net/corda/flask/launcher/JavaProcessBuilder.java
  flask/flask-launcher/src/main/java/net/corda/flask/launcher/Launcher.java
  flask/src/main/java/net/corda/gradle/flask/FlaskJarTask.java
  flask/src/main/java/net/corda/gradle/flask/HeartbeatAgentResource.java
  flask/src/main/java/net/corda/gradle/flask/LauncherResource.java
Labels: trivial

#377 CORE-855: A better fix for Gradle deprecation warnings.
  api-scanner/src/main/java/net/corda/plugins/apiscanner/ApiScanner.java
  api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java
  cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
  jar-filter/build.gradle
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterConfigurationTest.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterExecuteTest.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConfigurationTests.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixExecuteTest.kt
  jar-filter/src/test/resources/basic-execute/build.gradle
  jar-filter/src/test/resources/basic-execute/kotlin/net/corda/gradle/ExampleKotlin.kt
Labels: technical debt, trivial

#383 CORE-855: A better fix for deprecation warning in API Scanner and JarFilter. (#377)
  api-scanner/src/main/java/net/corda/plugins/apiscanner/ApiScanner.java
  api-scanner/src/main/java/net/corda/plugins/apiscanner/ScanApi.java
  cordapp/src/main/kotlin/net/corda/plugins/CordappPlugin.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/JarFilterTask.kt
  jar-filter/src/main/kotlin/net/corda/gradle/jarfilter/MetaFixerTask.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterConfigurationTest.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterExecuteTest.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixConfigurationTests.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixExecuteTest.kt
  jar-filter/src/test/resources/basic-execute/build.gradle
  jar-filter/src/test/resources/basic-execute/kotlin/net/corda/gradle/ExampleKotlin.kt
Labels: backport, technical debt

#385 CORE-727: Generate a unique filename for flask temporary file.
  flask/src/main/java/net/corda/gradle/flask/FlaskJarTask.java
Labels: trivial

#386 CORE-727: Initialize new ZipEntry objects more thoroughly.
  flask/src/main/java/net/corda/gradle/flask/FlaskJarTask.java
  flask/src/test/groovy/net/corda/gradle/flask/FlaskPluginTest.groovy
Labels: bug

#388 NOTICK: Enable debugging for two JarFilter test projects.
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterTimestampTest.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixTimestampTest.kt
Labels: technical debt, trivial

#389 NOTICK: Enable debugging for two JarFilter test projects. (#388)
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/JarFilterTimestampTest.kt
  jar-filter/src/test/kotlin/net/corda/gradle/jarfilter/MetaFixTimestampTest.kt
Labels: backport, technical debt, trivial
